In [1]:
# ============================================================
# AgriIntel
#
# Phase 3
#
# Data Cleaning & Preprocessing
# ============================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
crop_df = pd.read_csv("../data/raw/crop_production.csv")
yield_df = pd.read_csv("../data/raw/crop_yield.csv")
weather_df = pd.read_csv("../data/raw/state_weather.csv")
soil_df = pd.read_csv("../data/raw/state_soil.csv")

In [3]:
# Create a copy to preserve original data

crop_clean = crop_df.copy()
yield_clean = yield_df.copy()
weather_clean = weather_df.copy()
soil_clean = soil_df.copy()

In [4]:
crop_clean.isnull().sum()

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [5]:
crop_clean[crop_clean["Crop"].isnull()]

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
345375,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345376,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2018-19,Winter,NaN,Hectare,NaN,Tonnes,NaN
345377,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345378,Daman and Diu,DIU,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345379,Daman and Diu,DAMAN,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345380,Manipur,BISHNUPUR,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345381,Manipur,CHANDEL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345382,Manipur,CHURACHANDPUR,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345383,Manipur,IMPHAL EAST,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345384,Manipur,IMPHAL WEST,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345385,Manipur,SENAPATI,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345386,Manipur,TAMENGLONG,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345387,Manipur,THOUBAL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345388,Manipur,UKHRUL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345389,Manipur,BISHNUPUR,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345390,Manipur,CHANDEL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345391,Manipur,CHURACHANDPUR,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345392,Manipur,IMPHAL EAST,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345393,Manipur,IMPHAL WEST,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345394,Manipur,SENAPATI,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345395,Manipur,TAMENGLONG,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345396,Manipur,THOUBAL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345397,Manipur,UKHRUL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345398,Manipur,BISHNUPUR,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345399,Manipur,CHANDEL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345400,Manipur,CHURACHANDPUR,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345401,Manipur,IMPHAL EAST,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345402,Manipur,IMPHAL WEST,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345403,Manipur,SENAPATI,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345404,Manipur,TAMENGLONG,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345405,Manipur,THOUBAL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345406,Manipur,UKHRUL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN

In [6]:
crop_clean[crop_clean["Area"].isnull()]

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
294263,Telangana,THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU,Wheat,2019-20,NaN,NaN,Hectare,NaN,Tonnes,NaN
345375,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345376,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2018-19,Winter,NaN,Hectare,NaN,Tonnes,NaN
345377,Dadra and Nagar Haveli,DADRA AND NAGAR HAVELI,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345378,Daman and Diu,DIU,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345379,Daman and Diu,DAMAN,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345380,Manipur,BISHNUPUR,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345381,Manipur,CHANDEL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345382,Manipur,CHURACHANDPUR,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345383,Manipur,IMPHAL EAST,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345384,Manipur,IMPHAL WEST,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345385,Manipur,SENAPATI,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345386,Manipur,TAMENGLONG,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345387,Manipur,THOUBAL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345388,Manipur,UKHRUL,NaN,2019-20,Kharif,NaN,Hectare,NaN,Tonnes,NaN
345389,Manipur,BISHNUPUR,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345390,Manipur,CHANDEL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345391,Manipur,CHURACHANDPUR,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345392,Manipur,IMPHAL EAST,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345393,Manipur,IMPHAL WEST,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345394,Manipur,SENAPATI,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345395,Manipur,TAMENGLONG,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345396,Manipur,THOUBAL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345397,Manipur,UKHRUL,NaN,2019-20,Whole Year,NaN,Hectare,NaN,Tonnes,NaN
345398,Manipur,BISHNUPUR,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345399,Manipur,CHANDEL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345400,Manipur,CHURACHANDPUR,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345401,Manipur,IMPHAL EAST,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345402,Manipur,IMPHAL WEST,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345403,Manipur,SENAPATI,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345404,Manipur,TAMENGLONG,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345405,Manipur,THOUBAL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345406,Manipur,UKHRUL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN

In [7]:
crop_clean[crop_clean["Production"].isnull()]

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
138,Andhra Pradesh,NIZAMABAD,Arhar/Tur,2002-03,Rabi,1.0,Hectare,NaN,Tonnes,0.0
252,Andhra Pradesh,RANGAREDDI,Bajra,2002-03,Rabi,1.0,Hectare,NaN,Tonnes,0.0
266,Andhra Pradesh,VISAKHAPATANAM,Bajra,2002-03,Rabi,2.0,Hectare,NaN,Tonnes,0.0
294,Andhra Pradesh,KARIMNAGAR,Banana,2001-02,Whole Year,1.0,Hectare,NaN,Tonnes,0.0
305,Andhra Pradesh,MAHBUBNAGAR,Banana,2001-02,Whole Year,12.0,Hectare,NaN,Tonnes,0.0
...,...,...,...,...,...,...,...,...,...,...
345402,Manipur,IMPHAL WEST,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345403,Manipur,SENAPATI,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345404,Manipur,TAMENGLONG,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345405,Manipur,THOUBAL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN
345406,Manipur,UKHRUL,NaN,2019-20,Rabi,NaN,Hectare,NaN,Tonnes,NaN

In [8]:
# Crop name is mandatory.
# Rows without crop information cannot be analyzed.

crop_clean.dropna(subset=["Crop"], inplace=True)

In [9]:
crop_clean.dropna(subset=["Season"], inplace=True)

In [10]:
crop_clean["Area"].isnull().sum()

np.int64(0)

In [11]:
crop_clean["Area"] = crop_clean["Area"].fillna(
    crop_clean["Area"].median()
)

In [12]:
crop_clean["Yield"] = crop_clean["Yield"].fillna(
    crop_clean["Yield"].median()
)

In [14]:
crop_clean["Production"].isnull().sum()

# Production is the target variable of the project. Missing production values should not be imputed without domain knowledge because it may introduce bias.

np.int64(4960)

In [15]:
crop_clean = crop_clean.drop_duplicates()

In [16]:
text_columns = [
    "State",
    "District",
    "Crop",
    "Season"
]

for col in text_columns:
    crop_clean[col] = (
        crop_clean[col]
        .str.strip()
        .str.title()
    )

In [17]:
yield_clean.columns

Index(['crop', 'year', 'season', 'state', 'area', 'production', 'fertilizer',
       'pesticide', 'yield'],
      dtype='object')

In [18]:
yield_clean["crop"] = yield_clean["crop"].str.strip().str.title()

yield_clean["state"] = yield_clean["state"].str.strip().str.title()

yield_clean["season"] = yield_clean["season"].str.strip().str.title()

In [19]:
weather_clean["state"] = weather_clean["state"].str.strip().str.title()

In [20]:
soil_clean["state"] = soil_clean["state"].str.strip().str.title()

In [21]:
(crop_clean["Area"] < 0).sum()

np.int64(0)

In [22]:
(crop_clean["Production"] < 0).sum()

np.int64(0)

In [23]:
(crop_clean["Yield"] < 0).sum()

np.int64(0)

In [25]:
crop_clean[crop_clean["Production"] == 0]

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
361,Andhra Pradesh,Mahbubnagar,Cashewnut,2003-04,Whole Year,3.0,Hectare,0.0,Tonnes,0.0
369,Andhra Pradesh,Rangareddi,Cashewnut,2003-04,Whole Year,3.0,Hectare,0.0,Tonnes,0.0
1208,Andhra Pradesh,Kurnool,Linseed,2003-04,Rabi,1.0,Hectare,0.0,Tonnes,0.0
2214,Andhra Pradesh,Adilabad,Soyabean,2002-03,Kharif,38558.0,Hectare,0.0,Tonnes,0.0
2216,Andhra Pradesh,Anantapur,Soyabean,2002-03,Kharif,51.0,Hectare,0.0,Tonnes,0.0
...,...,...,...,...,...,...,...,...,...,...
329974,Punjab,Nawanshahr,Sesamum,1999-00,Kharif,100.0,Hectare,0.0,Tonnes,0.0
330252,Rajasthan,Bikaner,Bajra,1999-00,Kharif,131853.0,Hectare,0.0,Tonnes,0.0
332014,Rajasthan,Barmer,Other Kharif Pulses,1999-00,Kharif,3.0,Hectare,0.0,Tonnes,0.0
332703,Rajasthan,Jodhpur,Small Millets,1999-00,Kharif,30.0,Hectare,0.0,Tonnes,0.0
332706,Rajasthan,Rajsamand,Small Millets,1999-00,Kharif,2.0,Hectare,0.0,Tonnes,0.0

In [26]:
crop_clean["Area Units"].value_counts()

Area Units
Hectare    345374
Name: count, dtype: int64

In [27]:
crop_clean["Production Units"].value_counts()

Production Units
Tonnes    331653
Bales      10794
Nuts        2927
Name: count, dtype: int64

In [40]:
crop_clean.dtypes

State                object
District             object
Crop                 object
Year                 object
Season               object
Area                float64
Area Units           object
Production          float64
Production Units     object
Yield               float64
dtype: object

In [42]:
crop_clean.to_csv(
    "../data/processed/crop_production_clean.csv",
    index=False
)

yield_clean.to_csv(
    "../data/processed/crop_yield_clean.csv",
    index=False
)

weather_clean.to_csv(
    "../data/processed/state_weather_clean.csv",
    index=False
)

soil_clean.to_csv(
    "../data/processed/state_soil_clean.csv",
    index=False
)

In [43]:
crop_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 345374 entries, 0 to 345374
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345374 non-null  object
 1   District          345374 non-null  object
 2   Crop              345374 non-null  object
 3   Year              345374 non-null  object
 4   Season            345374 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345374 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345374 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 29.0+ MB

In [44]:
summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Crop",
        "Missing Season",
        "Missing Area",
        "Missing Yield",
        "Missing Production",
        "Duplicate Rows"
    ],
    "Value": [
        len(crop_clean),
        crop_clean.shape[1],
        crop_clean["Crop"].isnull().sum(),
        crop_clean["Season"].isnull().sum(),
        crop_clean["Area"].isnull().sum(),
        crop_clean["Yield"].isnull().sum(),
        crop_clean["Production"].isnull().sum(),
        crop_clean.duplicated().sum()
    ]
})

summary

               Metric   Value
0                Rows  345374
1             Columns      10
2        Missing Crop       0
3      Missing Season       0
4        Missing Area       0
5       Missing Yield       0
6  Missing Production    4960
7      Duplicate Rows       0