In [1]:
# # 🌾 AgriIntel

# ## Phase 6A

# # Feature Engineering

# ### Objective

# Feature Engineering is the process of creating new meaningful variables from
# existing data.

# In this phase we will create

# • Time Features

# • Climate Features

# These engineered features will improve analytical insights and machine learning performance.

In [2]:
# ============================================================
# AgriIntel
#
# Phase 6A
#
# Feature Engineering
#
# Time Intelligence
#
# Climate Intelligence
# ============================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

In [3]:
master = pd.read_csv("../data/merged/master_dataset.csv")

In [4]:
print("="*60)

print("MASTER DATASET")

print("="*60)

print("Shape :",master.shape)

print()

print(master.head())

print()

master.info()

============================================================
MASTER DATASET
============================================================
Shape : (345374, 25)

                         State                  District      Crop     Year  \
0  Andaman And Nicobar Islands                  Nicobars  Arecanut  2001-02
1  Andaman And Nicobar Islands                  Nicobars  Arecanut  2002-03
2  Andaman And Nicobar Islands                  Nicobars  Arecanut  2003-04
3  Andaman And Nicobar Islands  North And Middle Andaman  Arecanut  2001-02
4  Andaman And Nicobar Islands            South Andamans  Arecanut  2002-03

       Season    Area Area Units  Production Production Units     Yield  \
0      Kharif  1254.0    Hectare      2061.0           Tonnes  1.643541
1  Whole Year  1258.0    Hectare      2083.0           Tonnes  1.655803
2  Whole Year  1261.0    Hectare      1525.0           Tonnes  1.209358
3      Kharif  3100.0    Hectare      5239.0           Tonnes  1.690000
4  Whole Year  3105.0    Hectare      5267.0           Tonnes  1.696296

   Start_Year  Year_yield  Area_yield  Production_yield  fertilizer  \
0        2001         NaN         NaN               NaN         NaN
1        2002         NaN         NaN               NaN         NaN
2        2003         NaN         NaN               NaN         NaN
3        2001         NaN         NaN               NaN         NaN
4        2002         NaN         NaN               NaN         NaN

   pesticide  Yield_yield  Year_weather  avg_temp_c  total_rainfall_mm  \
0        NaN          NaN           NaN         NaN                NaN
1        NaN          NaN           NaN         NaN                NaN
2        NaN          NaN           NaN         NaN                NaN
3        NaN          NaN           NaN         NaN                NaN
4        NaN          NaN           NaN         NaN                NaN

   avg_humidity_percent   N   P   K  pH
0                   NaN NaN NaN NaN NaN
1                   NaN NaN NaN NaN NaN
2                   NaN NaN NaN NaN NaN
3                   NaN NaN NaN NaN NaN
4                   NaN NaN NaN NaN NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345374 entries, 0 to 345373
Data columns (total 25 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   State                 345374 non-null  object
 1   District              345374 non-null  object
 2   Crop                  345374 non-null  object
 3   Year                  345374 non-null  object
 4   Season                345374 non-null  object
 5   Area                  345374 non-null  float64
 6   Area Units            345374 non-null  object
 7   Production            340414 non-null  float64
 8   Production Units      345374 non-null  object
 9   Yield                 345374 non-null  float64
 10  Start_Year            345374 non-null  int64
 11  Year_yield            318023 non-null  float64
 12  Area_yield            318023 non-null  float64
 13  Production_yield      318023 non-null  float64
 14  fertilizer            318023 non-null  float64
 15  pesticide             318023 non-null  float64
 16  Yield_yield           318023 non-null  float64
 17  Year_weather          323787 non-null  float64
 18  avg_temp_c            323787 non-null  float64
 19  total_rainfall_mm     323787 non-null  float64
 20  avg_humidity_percent  323787 non-null  float64
 21  N                     323787 non-null  float64
 22  P                     323787 non-null  float64
 23  K                     323787 non-null  float64
 24  pH                    323787 non-null  float64
dtypes: float64(17), int64(1), object(7)
memory usage: 65.9+ MB

In [5]:
master.isnull().sum()

State                       0
District                    0
Crop                        0
Year                        0
Season                      0
Area                        0
Area Units                  0
Production               4960
Production Units            0
Yield                       0
Start_Year                  0
Year_yield              27351
Area_yield              27351
Production_yield        27351
fertilizer              27351
pesticide               27351
Yield_yield             27351
Year_weather            21587
avg_temp_c              21587
total_rainfall_mm       21587
avg_humidity_percent    21587
N                       21587
P                       21587
K                       21587
pH                      21587
dtype: int64

In [6]:
# TIME FEATURE ENGINEERING

In [7]:
master[["Year","Start_Year"]].head(10)

      Year  Start_Year
0  2001-02        2001
1  2002-03        2002
2  2003-04        2003
3  2001-02        2001
4  2002-03        2002
5  2003-04        2003
6  2002-03        2002
7  2003-04        2003
8  2002-03        2002
9  2003-04        2003

In [8]:
# Extract ending year from agricultural year

master["End_Year"]=(
master["Year"]
.str.split("-")
.str[1]
.astype(int)
)

# Convert

master["End_Year"]=master["Start_Year"].floordiv(100)*100+master["End_Year"]

master[["Year","Start_Year","End_Year"]].head()

      Year  Start_Year  End_Year
0  2001-02        2001      2002
1  2002-03        2002      2003
2  2003-04        2003      2004
3  2001-02        2001      2002
4  2002-03        2002      2003

In [9]:
master["Decade"]=(
master["Start_Year"]//10
)*10

In [10]:
master["Decade"].value_counts().sort_index()

Decade
1990     33852
2000    143808
2010    167395
2020       319
Name: count, dtype: int64

In [11]:
bins=[1996,2000,2005,2010,2015,2025]

labels=[

"1997-2000",

"2001-2005",

"2006-2010",

"2011-2015",

"2016-2020"

]

master["Year_Group"]=pd.cut(

master["Start_Year"],

bins=bins,

labels=labels

)

In [12]:
master["Year_Group"].value_counts()

Year_Group
2011-2015    79515
2006-2010    74739
2016-2020    73310
2001-2005    70365
1997-2000    47445
Name: count, dtype: int64

In [13]:
# CLIMATE FEATURE ENGINEERING

In [ ]:
master["Rainfall_Category"]=pd.cut(

master["total_rainfall_mm"],

bins=[0,700,1200,5000],

labels=[

"Low",

"Medium",

"High"

]

)

In [18]:
master["Rainfall_Category"].value_counts()

# Agricultural productivity depends heavily on rainfall.

Rainfall_Category
Medium    153535
High      143507
Low        26443
Name: count, dtype: int64

In [19]:
master["Temperature_Category"]=pd.cut(

master["avg_temp_c"],

bins=[0,20,30,50],

labels=[

"Cool",

"Moderate",

"Hot"

]

)

In [20]:
master["Temperature_Category"].value_counts()

Temperature_Category
Moderate    301450
Cool         22337
Hot              0
Name: count, dtype: int64

In [21]:
master["Humidity_Category"]=pd.cut(

master["avg_humidity_percent"],

bins=[0,50,70,100],

labels=[

"Low",

"Medium",

"High"

]

)

In [22]:
master["Humidity_Category"].value_counts()

Humidity_Category
Medium    170353
High      107449
Low        45985
Name: count, dtype: int64

In [23]:
master[

[

"avg_temp_c",

"Temperature_Category",

"total_rainfall_mm",

"Rainfall_Category",

"avg_humidity_percent",

"Humidity_Category"

]

].head(10)

,avg_temp_c,Temperature_Category,total_rainfall_mm,Rainfall_Category,avg_humidity_percent,Humidity_Category
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
feature_report=pd.DataFrame({

"Feature":[

"End_Year",

"Decade",

"Year_Group",

"Rainfall_Category",

"Temperature_Category",

"Humidity_Category"

],

"Purpose":[

"Agricultural Season",

"Trend Analysis",

"Historical Comparison",

"Climate Analysis",

"Climate Analysis",

"Climate Analysis"

]

})

feature_report

                Feature                Purpose
0              End_Year    Agricultural Season
1                Decade         Trend Analysis
2            Year_Group  Historical Comparison
3     Rainfall_Category       Climate Analysis
4  Temperature_Category       Climate Analysis
5     Humidity_Category       Climate Analysis

In [25]:
master.shape

(345374, 31)

In [26]:
master.to_csv(

"../data/final/master_dataset_featured.csv",

index=False

)

In [27]:
print("="*60)

print("PHASE 6A VERIFICATION")

print("="*60)

print()

print("Dataset Shape")

print(master.shape)

print()

print("New Features")

new_features=[

"End_Year",

"Decade",

"Year_Group",

"Rainfall_Category",

"Temperature_Category",

"Humidity_Category"

]

print(new_features)

print()

print(master[new_features].head())

print()

print("Missing Values")

print(master[new_features].isnull().sum())

print()

print("Feature Report")

print(feature_report)

============================================================
PHASE 6A VERIFICATION
============================================================

Dataset Shape
(345374, 31)

New Features
['End_Year', 'Decade', 'Year_Group', 'Rainfall_Category', 'Temperature_Category', 'Humidity_Category']

   End_Year  Decade Year_Group Rainfall_Category Temperature_Category  \
0      2002    2000  2001-2005               NaN                  NaN
1      2003    2000  2001-2005               NaN                  NaN
2      2004    2000  2001-2005               NaN                  NaN
3      2002    2000  2001-2005               NaN                  NaN
4      2003    2000  2001-2005               NaN                  NaN

  Humidity_Category
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN

Missing Values
End_Year                    0
Decade                      0
Year_Group                  0
Rainfall_Category       21889
Temperature_Category    21587
Humidity_Category       21587
dtype: int64

Feature Report
                Feature                Purpose
0              End_Year    Agricultural Season
1                Decade         Trend Analysis
2            Year_Group  Historical Comparison
3     Rainfall_Category       Climate Analysis
4  Temperature_Category       Climate Analysis
5     Humidity_Category       Climate Analysis

In [28]:
master[
[
    "avg_temp_c",
    "total_rainfall_mm",
    "avg_humidity_percent"
]
].isnull().sum()

avg_temp_c              21587
total_rainfall_mm       21587
avg_humidity_percent    21587
dtype: int64

In [29]:
master[
[
    "avg_temp_c",
    "total_rainfall_mm",
    "avg_humidity_percent"
]
].describe()

          avg_temp_c  total_rainfall_mm  avg_humidity_percent
count  323787.000000      323787.000000         323787.000000
mean       24.958929        1288.227617             62.211115
std         3.124040         576.713263             10.992322
min         6.260000         249.240000             34.470000
25%        23.940000         895.930000             52.650000
50%        25.830000        1131.170000             62.280000
75%        26.650000        1558.440000             72.000000
max        28.630000        5244.360000             86.060000

In [30]:
master[
[
    "State",
    "Year",
    "avg_temp_c"
]
].dropna().head(20)

             State     Year  avg_temp_c
54  Andhra Pradesh  2001-02       28.08
55  Andhra Pradesh  2002-03       28.54
56  Andhra Pradesh  2003-04       28.31
57  Andhra Pradesh  2001-02       28.08
58  Andhra Pradesh  2002-03       28.54
59  Andhra Pradesh  2003-04       28.31
60  Andhra Pradesh  2001-02       28.08
61  Andhra Pradesh  2002-03       28.54
62  Andhra Pradesh  2003-04       28.31
63  Andhra Pradesh  2002-03       28.54
64  Andhra Pradesh  2003-04       28.31
65  Andhra Pradesh  2003-04       28.31
66  Andhra Pradesh  2001-02       28.08
67  Andhra Pradesh  2001-02       28.08
68  Andhra Pradesh  2002-03       28.54
69  Andhra Pradesh  2002-03       28.54
70  Andhra Pradesh  2003-04       28.31
71  Andhra Pradesh  2003-04       28.31
72  Andhra Pradesh  2001-02       28.08
73  Andhra Pradesh  2001-02       28.08

In [32]:
master[
    master["avg_temp_c"].notna()
][
[
    "State",
    "Year",
    "avg_temp_c",
    "Temperature_Category",
    "total_rainfall_mm",
    "Rainfall_Category",
    "avg_humidity_percent",
    "Humidity_Category"
]
].head(20)

,State,Year,avg_temp_c,Temperature_Category,total_rainfall_mm,Rainfall_Category,avg_humidity_percent,Humidity_Category
54,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
55,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
56,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
57,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
58,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
59,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
60,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
61,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
62,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
63,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
64,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
65,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
66,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
67,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
68,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
69,Andhra Pradesh,2002-03,28.54,Moderate,768.22,Medium,66.52,Medium
70,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
71,Andhra Pradesh,2003-04,28.31,Moderate,857.23,Medium,68.83,Medium
72,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium
73,Andhra Pradesh,2001-02,28.08,Moderate,910.13,Medium,68.69,Medium

In [33]:
# PHASE 6B – Business Feature Engineering & Intelligence Features

In [34]:
# ==========================================================
# PHASE 6B
# AGRICULTURE BUSINESS FEATURES
# ==========================================================

import numpy as np

# ----------------------------------------------------------
# Production Per Hectare
# ----------------------------------------------------------
# Measures actual productivity.

master["Production_per_Hectare"] = (
    master["Production"] / master["Area"]
)

# ----------------------------------------------------------
# Fertilizer Efficiency
# ----------------------------------------------------------
# Fertilizer required per hectare.

master["Fertilizer_per_Hectare"] = (
    master["fertilizer"] / master["Area_yield"]
)

# ----------------------------------------------------------
# Pesticide Efficiency
# ----------------------------------------------------------
# Pesticide required per hectare.

master["Pesticide_per_Hectare"] = (
    master["pesticide"] / master["Area_yield"]
)

# ----------------------------------------------------------
# Rainfall Intensity
# ----------------------------------------------------------

master["Rainfall_per_Hectare"] = (
    master["total_rainfall_mm"] / master["Area"]
)

In [35]:
master[
[
"Production_per_Hectare",
"Fertilizer_per_Hectare",
"Pesticide_per_Hectare",
"Rainfall_per_Hectare"
]
].head()

,Production_per_Hectare,Fertilizer_per_Hectare,Pesticide_per_Hectare,Rainfall_per_Hectare
0,1.643541,NaN,NaN,NaN
1,1.655803,NaN,NaN,NaN
2,1.209358,NaN,NaN,NaN
3,1.690000,NaN,NaN,NaN
4,1.696296,NaN,NaN,NaN

In [36]:
# ==========================================================
# Crop Category Mapping
# ==========================================================

cereals = [
    "Rice","Wheat","Maize","Barley","Jowar","Bajra","Ragi"
]

pulses = [
    "Gram","Arhar/Tur","Moong","Urad","Masoor"
]

oilseeds = [
    "Groundnut",
    "Soyabean",
    "Mustard",
    "Sunflower",
    "Sesamum"
]

fruits = [
    "Banana",
    "Mango",
    "Apple",
    "Orange",
    "Grapes"
]

vegetables = [
    "Potato",
    "Onion",
    "Tomato",
    "Cabbage"
]

def crop_category(crop):

    crop=str(crop)

    if crop in cereals:
        return "Cereal"

    elif crop in pulses:
        return "Pulse"

    elif crop in oilseeds:
        return "Oilseed"

    elif crop in fruits:
        return "Fruit"

    elif crop in vegetables:
        return "Vegetable"

    else:
        return "Other"

master["Crop_Category"]=master["Crop"].apply(crop_category)

In [37]:
master["Crop_Category"].value_counts()

Crop_Category
Other        156656
Cereal        82578
Pulse         42333
Oilseed       37867
Vegetable     21431
Fruit          4509
Name: count, dtype: int64

In [38]:
# ==========================================================
# Production Level
# ==========================================================

master["Production_Level"] = pd.qcut(

    master["Production"],

    q=3,

    labels=[
        "Low",
        "Medium",
        "High"
    ]

)

# ==========================================================
# Yield Level
# ==========================================================

master["Yield_Level"] = pd.qcut(

    master["Yield"],

    q=3,

    labels=[
        "Low",
        "Medium",
        "High"
    ]

)

In [39]:
master[
[
"Production_Level",
"Yield_Level"
]
].head()

  Production_Level Yield_Level
0           Medium      Medium
1           Medium      Medium
2           Medium      Medium
3             High      Medium
4             High      Medium

In [40]:
# ==========================================================
# Weather Available
# ==========================================================

master["Weather_Data_Available"]=(

master["avg_temp_c"].notna()

)

# ==========================================================
# Soil Available
# ==========================================================

master["Soil_Data_Available"]=(

master["N"].notna()

)

In [41]:
master[
[
"Weather_Data_Available",
"Soil_Data_Available"
]
].head(15)

    Weather_Data_Available  Soil_Data_Available
0                    False                False
1                    False                False
2                    False                False
3                    False                False
4                    False                False
5                    False                False
6                    False                False
7                    False                False
8                    False                False
9                    False                False
10                   False                False
11                   False                False
12                   False                False
13                   False                False
14                   False                False

In [42]:
print("="*70)
print("PHASE 6B VERIFICATION")
print("="*70)

print("\nDataset Shape")
print(master.shape)

print("\nNew Columns")

print([

"Production_per_Hectare",

"Fertilizer_per_Hectare",

"Pesticide_per_Hectare",

"Rainfall_per_Hectare",

"Crop_Category",

"Production_Level",

"Yield_Level",

"Weather_Data_Available",

"Soil_Data_Available"

])

print("\n")

display(

master[
[
"Production_per_Hectare",

"Fertilizer_per_Hectare",

"Pesticide_per_Hectare",

"Rainfall_per_Hectare",

"Crop_Category",

"Production_Level",

"Yield_Level",

"Weather_Data_Available",

"Soil_Data_Available"

]
].head()

)

print("\nBusiness Purpose")

summary=pd.DataFrame({

"Feature":[

"Production_per_Hectare",

"Fertilizer_per_Hectare",

"Pesticide_per_Hectare",

"Rainfall_per_Hectare",

"Crop_Category",

"Production_Level",

"Yield_Level",

"Weather_Data_Available",

"Soil_Data_Available"

],

"Purpose":[

"Crop Productivity",

"Fertilizer Analysis",

"Pesticide Analysis",

"Rainfall Efficiency",

"Crop Segmentation",

"Business Intelligence",

"Yield Intelligence",

"Weather Availability",

"Soil Availability"

]

})

display(summary)

======================================================================
PHASE 6B VERIFICATION
======================================================================

Dataset Shape
(345374, 40)

New Columns
['Production_per_Hectare', 'Fertilizer_per_Hectare', 'Pesticide_per_Hectare', 'Rainfall_per_Hectare', 'Crop_Category', 'Production_Level', 'Yield_Level', 'Weather_Data_Available', 'Soil_Data_Available']

,Production_per_Hectare,Fertilizer_per_Hectare,Pesticide_per_Hectare,Rainfall_per_Hectare,Crop_Category,Production_Level,Yield_Level,Weather_Data_Available,Soil_Data_Available
0,1.643541,NaN,NaN,NaN,Other,Medium,Medium,False,False
1,1.655803,NaN,NaN,NaN,Other,Medium,Medium,False,False
2,1.209358,NaN,NaN,NaN,Other,Medium,Medium,False,False
3,1.690000,NaN,NaN,NaN,Other,High,Medium,False,False
4,1.696296,NaN,NaN,NaN,Other,High,Medium,False,False

Business Purpose

                  Feature                Purpose
0  Production_per_Hectare      Crop Productivity
1  Fertilizer_per_Hectare    Fertilizer Analysis
2   Pesticide_per_Hectare     Pesticide Analysis
3    Rainfall_per_Hectare    Rainfall Efficiency
4           Crop_Category      Crop Segmentation
5        Production_Level  Business Intelligence
6             Yield_Level     Yield Intelligence
7  Weather_Data_Available   Weather Availability
8     Soil_Data_Available      Soil Availability

In [43]:
master.to_csv(
    "../data/final/master_dataset_featured.csv",
    index=False
)